// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATVTIVDcYGN1wEra3FmkDWKI_2cLYF_aQ',
    appId: '1:882436085966:web:815eb7b12cca3c3daa589f',
    messagingSenderId: '882436085966',
    projectId: 'diemdanh-70701',
    authDomain: 'diemdanh-70701.firebaseapp.com',
    storageBucket: 'diemdanh-70701.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDUqwP1isLE4SdrP70XhmI6D8H4g1Wu9o',
    appId: '1:882436085966:android:9cc307247a8afe8daa589f',
    messagingSenderId: '882436085966',
    projectId: 'diemdanh-70701',
    storageBucket: 'diemdanh-70701.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG-leSy1LNGChAHC90NbMdQ6UE01iEX3Q',
    appId: '1:882436085966:ios:8f1411d1aaa93f2daa589f',
    messagingSenderId: '882436085966',
    projectId: 'diemdanh-70701',
    storageBucket: 'diemdanh-70701.firebasestorage.app',
    iosBundleId: 'com.example.diemDanh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG-leSy1LNGChAHC90NbMdQ6UE01iEX3Q',
    appId: '1:882436085966:ios:8f1411d1aaa93f2daa589f',
    messagingSenderId: '882436085966',
    projectId: 'diemdanh-70701',
    storageBucket: 'diemdanh-70701.firebasestorage.app',
    iosBundleId: 'com.example.diemDanh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATVTIVDcYGN1wEra3FmkDWKI_2cLYF_aQ',
    appId: '1:882436085966:web:c95e5c5032d0fc84aa589f',
    messagingSenderId: '882436085966',
    projectId: 'diemdanh-70701',
    authDomain: 'diemdanh-70701.firebaseapp.com',
    storageBucket: 'diemdanh-70701.firebasestorage.app',
  );

}
