// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApOdYcytY02RyxHFrTX2Y1hqEDEmRFml4',
    appId: '1:426208737194:web:c49201f900254925981dd3',
    messagingSenderId: '426208737194',
    projectId: 'diemdanh-ff855',
    authDomain: 'diemdanh-ff855.firebaseapp.com',
    storageBucket: 'diemdanh-ff855.firebasestorage.app',
    measurementId: 'G-WVRECQLSVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7jfChHTM2gUatPSCmoCHwUs2eMXSONiI',
    appId: '1:426208737194:android:a05f4fb63083c7ed981dd3',
    messagingSenderId: '426208737194',
    projectId: 'diemdanh-ff855',
    storageBucket: 'diemdanh-ff855.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBZvLbmPEpTGGbk7m_kF2xYRebvoPVMu8',
    appId: '1:426208737194:ios:07dd6bb167157cf9981dd3',
    messagingSenderId: '426208737194',
    projectId: 'diemdanh-ff855',
    storageBucket: 'diemdanh-ff855.firebasestorage.app',
    iosBundleId: 'com.example.diemDanh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBZvLbmPEpTGGbk7m_kF2xYRebvoPVMu8',
    appId: '1:426208737194:ios:07dd6bb167157cf9981dd3',
    messagingSenderId: '426208737194',
    projectId: 'diemdanh-ff855',
    storageBucket: 'diemdanh-ff855.firebasestorage.app',
    iosBundleId: 'com.example.diemDanh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApOdYcytY02RyxHFrTX2Y1hqEDEmRFml4',
    appId: '1:426208737194:web:c95101756e9b8730981dd3',
    messagingSenderId: '426208737194',
    projectId: 'diemdanh-ff855',
    authDomain: 'diemdanh-ff855.firebaseapp.com',
    storageBucket: 'diemdanh-ff855.firebasestorage.app',
    measurementId: 'G-G7CDZLJNJG',
  );

}